on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Display version
        run: ./gradlew --version

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew build --no-daemon

# https://github.com/gradle/wrapper-validation-action
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
