on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/axel-op/googlejavaformat-action/issues/11
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - if: github.event_name == 'pull_request'
        name: Lint code base
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Display version
        run: ./gradlew --version

      - run: ./gradlew build --no-daemon

# https://github.com/gradle/wrapper-validation-action
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
