on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      # https://github.com/axel-op/googlejavaformat-action
      - name: Lint code base
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --dry-run --set-exit-if-changed"
          version: 1.7
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Display version
        run: ./gradlew --version

      - run: ./gradlew build --no-daemon

# https://github.com/gradle/wrapper-validation-action
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
