on:
  release:
    types:
      - published

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Github release version and build.gradle version match
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          if [[ $(./gradlew -q printVersion) != "${RELEASE_TAG_NAME:1}" ]]
            then
              echo "Release tag (${RELEASE_TAG_NAME:1}) does not match the build.gradle version"
              exit 1
            else
              echo "Release tag matches the build.gradle version. Proceeding with publish_release workflow."
          fi

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'