on:
  release:
    types:
      - published

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Github release version and build.gradle version match
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          if [[ $(./gradlew -q printVersion) != "${RELEASE_TAG_NAME:1}" ]]
            then
              echo "Release tag (${RELEASE_TAG_NAME:1}) does not match the build.gradle version"
              exit 1
          fi
          echo "Release tag matches the build.gradle version. Proceeding with publish_release workflow."

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Publish package
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          # upload the ASCII-armored public key to https://keyserver.ubuntu.com/
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
